/* Protectoras */
INSERT INTO trackpetsdb.protectoras (id, correo_electronico, direccion, nombre_protectora, numero_entidad_social, telefono, sitio_web) VALUES ('1', 'protectora_sabadell@gmail.com', 'Ctra. de Sabadell a Caldes, km 24,2', 'Lliga protectora d\'animals de Sabadell', '25649', '937267227', 'http://www.protectorasabadell.org');
INSERT INTO trackpetsdb.protectoras (id, correo_electronico, direccion, nombre_protectora, numero_entidad_social, telefono, sitio_web) VALUES ('2', 'caldesanimal@caldesanimal.org', 'Caldes de Montbui, Carretera C-59. KM 15', 'Caldes animal, la prote', '12453', '666526181', 'http://www.caldesanimal.org');
INSERT INTO trackpetsdb.protectoras (id, correo_electronico, direccion, nombre_protectora, numero_entidad_social, telefono, sitio_web) VALUES ('3', 'info@protectorabcn.es', 'c/ Guarda Antón, 10 08035 - Barcelona España', 'Lliga per a la protecció d\'animals i plantes de Barcelona', '54897', '934170124', 'https://www.protectorabcn.es');
/* Perros */
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('1','Lorem...', '1001', '3', 1, 'https://cdn.pixabay.com/photo/2017/12/13/22/36/moscow-guard-dog-3017899__340.jpg', 'macho', 'rocky', 'mestizo', 'grande', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('2','Lorem...', '1010', '2', 1, 'https://cdn.pixabay.com/photo/2018/04/15/11/57/dog-3321496__340.jpg', 'macho', 'roco', 'mestizo', 'grande', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('3','Lorem...', '1011', '1', 1, 'https://cdn.pixabay.com/photo/2016/04/20/22/30/irish-setter-1342259__340.jpg', 'macho', 'bob', 'mestizo', 'mediano', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('4','Lorem...', '1100', '5', 1, 'https://cdn.pixabay.com/photo/2019/03/09/20/04/dog-4044915__340.jpg', 'macho', 'golber', 'mestizo', 'grande', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('5','Lorem...', '1101', '3', 1, 'https://cdn.pixabay.com/photo/2018/12/09/07/29/dog-3864458__340.jpg', 'hembra', 'mandy', 'mestizo', 'grande', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('6','Lorem...', '1110', '1', 1, 'https://cdn.pixabay.com/photo/2017/11/15/13/44/dog-2952030__340.jpg', 'macho', 'lucky', 'mestizo', 'mediano', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('7','Lorem...', '1111', '7', 1, 'https://cdn.pixabay.com/photo/2016/03/27/19/53/animal-1284004__340.jpg', 'macho', 'pancho', 'mestizo', 'grande', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('8','Lorem...', '2001', '8', 1, 'https://cdn.pixabay.com/photo/2017/08/26/19/18/red-dog-2683999__340.jpg', 'macho', 'gus', 'mestizo', 'mediano', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('9','Lorem...', '2010', '5', 1, 'https://cdn.pixabay.com/photo/2015/10/12/15/36/american-akita-984561__340.jpg', 'macho', 'linder', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('10','Lorem...', '2011', '3', 1, 'https://cdn.pixabay.com/photo/2016/06/13/06/49/dog-1453739__340.jpg', 'macho', 'dylan', 'mestizo', 'mediano', '1');

/* Gatos */
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('11','Lorem...', '2111', '1', 1, 'https://cdn.pixabay.com/photo/2014/05/07/06/44/cat-339400__340.jpg', 'macho', 'manchita', 'mestizo', 'pequeño', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('12','Lorem...', '2101', '4', 1, 'https://cdn.pixabay.com/photo/2015/11/15/22/09/cat-1044914__340.jpg', 'macho', 'tigerwoods', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('13','Lorem...', '3001', '5', 1, 'https://cdn.pixabay.com/photo/2018/03/27/17/25/cat-3266673__340.jpg', 'hembra', 'sophy', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('14','Lorem...', '3010', '3', 1, 'https://cdn.pixabay.com/photo/2018/06/03/08/57/cat-3449999__340.jpg', 'hembra', 'dina', 'mestizo', 'mediano', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('15','Lorem...', '3011', '3', 1, 'https://cdn.pixabay.com/photo/2014/10/01/10/46/cat-468232__340.jpg', 'hembra', 'cersei', 'mestizo', 'mediano', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('16','Lorem...', '3100', '1', 1, 'https://cdn.pixabay.com/photo/2016/11/29/01/10/adorable-1866475__340.jpg', 'macho', 'sharoo', 'mestizo', 'pequeño', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('17','Lorem...', '3101', '1', 1, 'https://cdn.pixabay.com/photo/2018/09/11/11/47/kitten-3669244__340.jpg', 'hembra', 'luna', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('18','Lorem...', '3111', '2', 1, 'https://cdn.pixabay.com/photo/2016/11/29/13/52/animal-1870003__340.jpg', 'macho', 'blanky', 'mestizo', 'mediano', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('19','Lorem...', '4000', '4', 1, 'https://cdn.pixabay.com/photo/2016/08/31/18/55/cat-1634369__340.jpg', 'macho', 'coco', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('20','Lorem...', '3000', '2', 1, 'https://cdn.pixabay.com/photo/2017/05/31/01/56/cat-2358830__340.jpg', 'hembra', 'candy', 'mestizo', 'mediano', '1');

/* Perros pequeños */
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('21','Lorem...', '4001', '1', 1, 'https://cdn.pixabay.com/photo/2020/05/03/13/09/puppy-5124947__340.jpg', 'macho', 'lucky', 'mestizo', 'pequeño', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('22','Lorem...', '4010', '2', 1, 'https://cdn.pixabay.com/photo/2016/01/05/17/51/dog-1123016__340.jpg', 'macho', 'pancho', 'mestizo', 'pequeño', '3');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('23','Lorem...', '4011', '1', 1, 'https://cdn.pixabay.com/photo/2019/12/30/16/07/chihuahua-4730005__340.jpg', 'macho', 'coco', 'mestizo', 'pequeño', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('24','Lorem...', '4100', '6', 1, 'https://cdn.pixabay.com/photo/2017/10/29/18/00/chihuahua-2900362__340.jpg', 'macho', 'bob', 'mestizo', 'pequeño', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('25','Lorem...', '4101', '1', 1, 'https://cdn.pixabay.com/photo/2015/11/17/15/24/puppy-1047722__340.jpg', 'macho', 'sharoo', 'mestizo', 'pequeño', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('26','Lorem...', '4110', '2', 1, 'https://cdn.pixabay.com/photo/2017/01/04/02/38/dog-1951211__340.jpg', 'macho', 'blanky', 'mestizo', 'pequeño', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('27','Lorem...', '4111', '3', 1, 'https://cdn.pixabay.com/photo/2016/12/28/16/25/chihuahua-1936395__340.jpg', 'hembra', 'lola', 'mestizo', 'pequeño', '3');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('28','Lorem...', '5000', '6', 1, 'https://cdn.pixabay.com/photo/2020/06/13/14/44/dog-5294497__340.jpg', 'macho', 'pancho', 'mestizo', 'pequeño', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('29','Lorem...', '5001', '3', 1, 'https://cdn.pixabay.com/photo/2016/04/24/23/27/chihuahua-1351002__340.jpg', 'macho', 'suertudo', 'mestizo', 'pequeño', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('30','Lorem...', '5010', '5', 1, 'https://cdn.pixabay.com/photo/2019/10/22/20/50/pug-4569812__340.jpg', 'macho', 'bob', 'mestizo', 'pequeño', '1');

/* Gatos mayores */
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('31','Lorem...', '6001', '5', 1, 'https://cdn.pixabay.com/photo/2019/09/22/16/47/old-cat-4496516__340.jpg', 'hembra', 'steve', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('32','Lorem...', '6010', '7', 1, 'https://cdn.pixabay.com/photo/2016/10/02/16/12/kermit-1709854__340.jpg', 'hembra', 'nina', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('33','Lorem...', '6011', '7', 1, 'https://cdn.pixabay.com/photo/2017/06/13/19/59/garden-cat-2399887__340.jpg', 'macho', 'bob', 'mestizo', 'mediano', '3');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('34','Lorem...', '6111', '8', 1, 'https://cdn.pixabay.com/photo/2019/01/04/22/22/cats-3914203__340.jpg', 'hembra', 'luna', 'mestizo', 'mediano', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('35','Lorem...', '7101', '8', 1, 'https://cdn.pixabay.com/photo/2015/12/18/20/57/cat-1099138__340.jpg', 'macho', 'rayas', 'mestizo', 'mediano', '3');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('36','Lorem...', '7111', '5', 1, 'https://cdn.pixabay.com/photo/2017/03/14/14/49/cat-2143332__340.jpg', 'macho', 'roco', 'mestizo', 'mediano', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('37','Lorem...', '7001', '1', 1, 'https://cdn.pixabay.com/photo/2017/08/23/08/33/cats-eyes-2671903__340.jpg', 'hembra', 'rango', 'mestizo', 'mediano', '3');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('38','Lorem...', '7011', '5', 1, 'https://cdn.pixabay.com/photo/2015/11/15/22/09/cat-1044914__340.jpg', 'macho', 'zarpas', 'mestizo', 'mediano', '3');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('39','Lorem...', '7101', '7', 1, 'https://cdn.pixabay.com/photo/2012/11/26/13/58/cat-67345__340.jpg', 'macho', 'luna', 'mestizo', 'mediano', '2');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('40','Lorem...', '7011', '6', 1, 'https://cdn.pixabay.com/photo/2018/06/03/08/57/cat-3449999__340.jpg', 'macho', 'candy', 'mestizo', 'mediano', '1');

/* Perros mayores */
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('41','Lorem...', '8000', '3', 1, 'https://cdn.pixabay.com/photo/2017/09/07/23/02/rhodesian-ridgeback-2727035__340.jpg', 'macho', 'bob', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('42','Lorem...', '8001', '3', 1, 'https://cdn.pixabay.com/photo/2017/08/22/13/36/dog-2668993__340.jpg', 'hembra', 'luna', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('43','Lorem...', '8010', '3', 1, 'https://cdn.pixabay.com/photo/2015/10/18/16/40/taxation-994707__340.jpg', 'macho', 'suertudo', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('44','Lorem...', '8011', '3', 1, 'https://cdn.pixabay.com/photo/2018/05/28/16/58/dog-3436427__340.jpg', 'hembra', 'coco', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('45','Lorem...', '8100', '3', 1, 'https://cdn.pixabay.com/photo/2019/10/08/09/22/dog-4534475__340.jpg', 'macho', 'bobby', 'mestizo', 'grande', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('46','Lorem...', '8101', '3', 1, 'https://cdn.pixabay.com/photo/2016/02/17/21/15/bernese-mountain-dog-1205918__340.jpg', 'macho', 'lola', 'mestizo', 'grande', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('47','Lorem...', '8111', '3', 1, 'https://cdn.pixabay.com/photo/2017/12/27/14/00/grass-3042744__340.jpg', 'hembra', 'candy', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('48','Lorem...', '9001', '3', 1, 'https://cdn.pixabay.com/photo/2017/10/19/23/13/dog-2869572__340.jpg', 'macho', 'teddy', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('49','Lorem...', '9010', '3', 1, 'https://cdn.pixabay.com/photo/2019/11/10/08/29/dog-4615198__340.jpg', 'hembra', 'linda', 'mestizo', 'mediano', '1');
INSERT INTO trackpetsdb.animales (id_animal, descripcion, dni_animal, edad, disponible, foto_url, genero, nombre, raza, tamanyo, id_protectora) VALUES ('50','Lorem...', '9011', '3', 1, 'https://cdn.pixabay.com/photo/2016/03/14/20/22/dog-1256219__340.jpg', 'macho', 'buddy', 'mestizo', 'grande', '1');
